/* DuelForge progression + Store/Forge + Profile + Friends. */
(function(){
'use strict';
const DF=window.DF=window.DF||{}, S=()=>DF.Supabase;
const CATALOG={
 armor_shadow:{category:'armor',name:'Shadow Armor',price:250,upgrade:180,max:5,desc:'Movement and dash efficiency',stats:{dashEfficiency:.08,speed:.04}},
 armor_royal:{category:'armor',name:'Royal Armor',price:350,upgrade:240,max:5,desc:'Balanced defense and power',stats:{defense:.05,power:.05}},
 armor_inferno:{category:'armor',name:'Inferno Armor',price:400,upgrade:280,max:5,desc:'Stronger power attacks',stats:{power:.10,defense:-.02}},
 armor_frost:{category:'armor',name:'Frost Armor',price:400,upgrade:280,max:5,desc:'Improved defense',stats:{defense:.10,speed:-.02}},
 power_berserk:{category:'power',name:'Berserk',price:300,upgrade:220,max:5,desc:'Temporary damage boost',stats:{type:'berserk',damage:.18,duration:2.2,cooldown:8}},
 power_shield:{category:'power',name:'Shield',price:300,upgrade:220,max:5,desc:'Temporary damage reduction',stats:{type:'shield',defense:.35,duration:2,cooldown:9}},
 power_lightning:{category:'power',name:'Lightning',price:450,upgrade:300,max:5,desc:'Long-range special strike',stats:{type:'lightning',damage:26,range:180,cooldown:7}},
 power_blood_rush:{category:'power',name:'Blood Rush',price:325,upgrade:230,max:5,desc:'Temporary speed boost',stats:{type:'bloodrush',speed:.28,duration:2,cooldown:8}},
 power_shadow_step:{category:'power',name:'Shadow Step',price:375,upgrade:260,max:5,desc:'Instant combat footwork',stats:{type:'shadowstep',distance:115,cooldown:6}},
 skin_ember:{category:'weapon_skin',name:'Ember Edge',price:200,upgrade:0,max:1,desc:'Crimson weapon accent',stats:{accent:'#ff5a3c'}},
 skin_frost:{category:'weapon_skin',name:'Frost Edge',price:200,upgrade:0,max:1,desc:'Frost weapon accent',stats:{accent:'#9bdcff'}},
 cosmetic_crown:{category:'cosmetic',name:'Warden Crown',price:250,upgrade:150,max:3,desc:'Royal head cosmetic',stats:{}},
 effect_void:{category:'effect',name:'Void Impact',price:300,upgrade:180,max:3,desc:'Dark impact effect',stats:{}}
};
const P={profile:{id:null,display_name:'PLAYER',coins:500,xp:0,rank:1,mp_wins:0,mp_losses:0,bot_wins:0,settings:{},bio:'',showcase_weapon:'sword'},items:[],friends:[],requests:[],duels:[]};
let ready=false,loading=false,loadPromise=null;
function notify(){try{DF.Progression&&DF.Progression.onChange&&DF.Progression.onChange(P)}catch(e){}}
function merge(payload){if(!payload)return;Object.assign(P.profile,payload.profile||{});P.items=payload.items||[];ready=true;render();notify()}
async function rpc(name,args){const s=S();if(!s)throw Error('Supabase is not configured.');const {data,error}=await s.rpc(name,args||{});if(error)throw error;return data}
async function load(){if(loading)return loadPromise;loading=true;loadPromise=(async()=>{const s=S();const ses=await s.auth.getSession();const uid=ses?.data?.session?.user?.id;if(!uid)throw Error('not authenticated');const data=await rpc('duelforge_get_progress');merge(data);return data})();try{return await loadPromise}catch(e){console.warn('Progression load failed:',e);throw e}finally{loading=false;loadPromise=null}}
function owned(id){return P.items.find(x=>x.id===id)}
function item(id){return CATALOG[id]||null}
function levelStats(c,l){const k=Math.max(0,l-1),out={};for(const x in c.stats)out[x]=typeof c.stats[x]==='number'?c.stats[x]*(1+k*.22):c.stats[x];return out}
function combat(){let armor=null,power=null,weaponSkin=null,effect=null,cosmetic=null;for(const it of P.items){if(!it.equipped)continue;const c=item(it.id);if(!c)continue;const x={id:it.id,level:it.level,stats:levelStats(c,it.level)};if(c.category==='armor')armor=x;else if(c.category==='power')power=x;else if(c.category==='weapon_skin')weaponSkin=x;else if(c.category==='effect')effect=x;else if(c.category==='cosmetic')cosmetic=x}return {armor,power,weaponSkin,effect,cosmetic}}
function catalogRows(){return Object.entries(CATALOG).map(([id,c])=>({id,...c}))}
async function buy(id){return merge(await rpc('duelforge_purchase_item',{p_item_id:id}))}
async function upgrade(id){return merge(await rpc('duelforge_upgrade_item',{p_item_id:id}))}
async function equip(id){return merge(await rpc('duelforge_equip_item',{p_item_id:id}))}
async function setName(name,settings){merge(await rpc('duelforge_set_profile',{p_name:name,p_settings:settings||null,p_bio:P.profile.bio||'',p_showcase_weapon:P.profile.showcase_weapon||'sword'}))}
async function setSettings(settings){merge(await rpc('duelforge_set_profile',{p_name:P.profile.display_name||'PLAYER',p_settings:settings||{},p_bio:P.profile.bio||'',p_showcase_weapon:P.profile.showcase_weapon||'sword'}))}
async function saveProfileExtras(bio,weapon){merge(await rpc('duelforge_set_profile',{p_name:P.profile.display_name||'PLAYER',p_settings:P.profile.settings||{},p_bio:String(bio||'').slice(0,240),p_showcase_weapon:(DF.WEAPONS&&DF.WEAPONS[weapon])?weapon:'sword'}))}
async function claim(matchId,won,rounds,ranked){merge(await rpc('duelforge_claim_match',{p_match_id:matchId,p_won:!!won,p_rounds:rounds|0,p_ranked:!!ranked}));return true}
async function leaderboard(){return await rpc('duelforge_leaderboard')}
async function searchPlayers(q){return await rpc('duelforge_search_players',{p_query:q})}
async function sendFriendRequest(name){return await rpc('duelforge_send_friend_request',{p_display_name:name})}
async function friendData(){const [friends,requests,duels]=await Promise.all([rpc('duelforge_friends'),rpc('duelforge_friend_requests'),rpc('duelforge_duel_requests')]);P.friends=friends||[];P.requests=requests||[];P.duels=duels||[];return {friends:P.friends,requests:P.requests,duels:P.duels}}
async function respondFriend(id,accept){return await rpc('duelforge_respond_friend_request',{p_request_id:id,p_accept:!!accept})}
async function createDuelRequest(friendId,roomCode){return await rpc('duelforge_create_duel_request',{p_friend_id:friendId,p_room_code:roomCode})}
async function respondDuel(id,accept){return await rpc('duelforge_respond_duel_request',{p_request_id:id,p_accept:!!accept})}
function itemIcon(c){let glyph=c.category==='armor'?'♜':c.category==='power'?'✦':c.category==='weapon_skin'?'⚔':c.category==='cosmetic'?'♛':'✹';if(c.id.includes('shadow'))glyph='◈';if(c.id.includes('frost'))glyph='❄';if(c.id.includes('inferno')||c.id.includes('ember'))glyph='🔥';if(c.id.includes('lightning'))glyph='ϟ';if(c.id.includes('shield'))glyph='⬡';if(c.id.includes('blood'))glyph='♢';if(c.id.includes('step'))glyph='➤';return `<div class="item-icon"><span>${glyph}</span></div>`}
function friendCard(x,actions){return `<div class="friend-row"><span class="avatar">${String((x.display_name||x.name||'?')[0]).replace(/[&<>"']/g,'')}</span><div><b>${String(x.display_name||x.name||'PLAYER').replace(/[&<>"']/g,'')}</b><small>${x.mp_wins??0} WINS · ${x.mp_losses??0} LOSSES</small></div><span class="friend-actions">${actions||''}</span></div>`}
async function refreshFriends(){try{const d=await friendData(),fr=document.getElementById('friendList'),rq=document.getElementById('friendRequests'),dq=document.getElementById('duelRequests');if(fr)fr.innerHTML=d.friends.length?d.friends.map(x=>friendCard(x,`<button class="secondary" data-duel="${x.id}">DUEL</button>`)).join(''):'<div class="message">No friends yet.</div>';if(rq)rq.innerHTML=d.requests.length?d.requests.map(x=>friendCard(x,`<button class="primary" data-accept="${x.id}">ACCEPT</button><button class="secondary" data-decline="${x.id}">DECLINE</button>`)).join(''):'<div class="message">No pending friend requests.</div>';if(dq)dq.innerHTML=d.duels.length?d.duels.map(x=>friendCard(x,`<button class="primary" data-join="${x.id}" data-room="${x.room_code}">JOIN DUEL</button>`)).join(''):'<div class="message">No duel requests.</div>';
 document.querySelectorAll('[data-accept]').forEach(b=>b.onclick=async()=>{await respondFriend(b.dataset.accept,true);refreshFriends()});document.querySelectorAll('[data-decline]').forEach(b=>b.onclick=async()=>{await respondFriend(b.dataset.decline,false);refreshFriends()});
 document.querySelectorAll('[data-join]').forEach(b=>b.onclick=async()=>{try{await respondDuel(b.dataset.join,true);await DF.joinRoomFromFriend?.(b.dataset.room)}catch(e){document.getElementById('friendMsg').textContent=e.message||'Could not join duel.'}});
 document.querySelectorAll('[data-duel]').forEach(b=>b.onclick=async()=>{try{const code=await DF.hostRoomForFriend?.(b.dataset.duel);if(code)document.getElementById('friendMsg').textContent='Duel request sent. Waiting for your friend…'}catch(e){document.getElementById('friendMsg').textContent=e.message||'Could not create duel.'}})
 }catch(e){const m=document.getElementById('friendMsg');if(m)m.textContent=e.message||'Could not load friends.'}}
async function searchFriend(){const q=document.getElementById('friendSearch').value.trim(),out=document.getElementById('friendSearchResults');if(q.length<2)return;try{const rows=await searchPlayers(q);out.innerHTML=(rows||[]).map(x=>`<div class="search-result"><span class="avatar">${String((x.display_name||'?')[0]).replace(/[&<>"']/g,'')}</span><b>${String(x.display_name).replace(/[&<>"']/g,'')}</b><button class="secondary" data-add="${String(x.display_name).replace(/"/g,'&quot;')}">ADD</button></div>`).join('')||'<div class="message">No players found.</div>';out.querySelectorAll('[data-add]').forEach(b=>b.onclick=async()=>{try{await sendFriendRequest(b.dataset.add);document.getElementById('friendMsg').textContent='Friend request sent.';refreshFriends()}catch(e){document.getElementById('friendMsg').textContent=e.message||'Request failed.'}})}catch(e){out.innerHTML='<div class="message bad">Search failed.</div>'}}
function inject(){if(document.getElementById('store'))return;const home=document.querySelector('.menu');if(home){const mk=(id,ico,title,sub)=>{const b=document.createElement('button');b.className='mbtn';b.id=id;b.innerHTML=`<span class="ico">${ico}</span><span class="lbl"><b>${title}</b><small>${sub}</small></span><span class="chev">›</span>`;return b};home.append(mk('storeBtn','⚒','Store / Forge','Buy, upgrade and equip gear'),mk('profileBtn','♜','Player Profile','XP, rank and inventory'),mk('friendsBtn','♟','Friends','Add friends and request duels'))}
const frag=document.createElement('div');frag.innerHTML=`
<section id="store" class="screen"><div class="sub-screen"><header class="sub-head"><button class="back" data-home>‹</button><h2>Store / Forge</h2></header><div class="forge-top"><div><small class="cap">COINS</small><b id="storeCoins">500</b></div><div><small class="cap">FORGE</small><span>Buy → Upgrade → Equip</span></div></div><div id="storeGrid" class="store-grid"></div><div id="storeMsg" class="message"></div></div></section>
<section id="profile" class="screen"><div class="sub-screen"><header class="sub-head"><button class="back" data-home>‹</button><h2>Player Profile</h2></header><div class="profile-card"><div class="avatar profile-avatar" id="profileAvatar">P</div><div><b id="profileName">PLAYER</b><small id="profileRank">RANK 1</small></div></div><div class="profile-stats"><div><b id="profileXp">0</b><small>XP</small></div><div><b id="profileWins">0</b><small>WINS</small></div><div><b id="profileLosses">0</b><small>LOSSES</small></div></div><div class="profile-editor"><h3>About Me</h3><textarea id="profileBio" maxlength="240" placeholder="Write a short bio..."></textarea><h3>Showcase Weapon</h3><div class="showcase-row"><select id="showcaseWeapon"></select><button class="primary" id="saveProfileExtras">SAVE PROFILE</button></div></div><h3>Equipped Gear</h3><div id="equippedList" class="equip-list"></div></div></section>
<section id="friends" class="screen"><div class="sub-screen"><header class="sub-head"><button class="back" data-home>‹</button><h2>Friends</h2></header><div class="friend-add card"><h3>Add Friend</h3><div class="field"><input id="friendSearch" maxlength="14" placeholder="Search gamertag"><button class="primary" id="friendSearchBtn">SEARCH</button></div><div id="friendSearchResults"></div></div><h3>Friend Requests</h3><div id="friendRequests" class="friend-list"></div><h3>Your Friends</h3><div id="friendList" class="friend-list"></div><h3>Duel Requests</h3><div id="duelRequests" class="friend-list"></div><div id="friendMsg" class="message"></div></div></section>`;
document.getElementById('app').append(...frag.children);
document.getElementById('storeBtn').onclick=()=>DF.show?.('store');document.getElementById('profileBtn').onclick=()=>DF.show?.('profile');document.getElementById('friendsBtn').onclick=()=>{DF.show?.('friends');refreshFriends()};document.getElementById('saveProfileExtras').onclick=async()=>{try{await saveProfileExtras(document.getElementById('profileBio').value,document.getElementById('showcaseWeapon').value);document.getElementById('friendMsg').textContent='Profile saved.'}catch(e){document.getElementById('friendMsg').textContent=e.message||'Could not save profile.'}render()};document.getElementById('friendSearchBtn').onclick=searchFriend;document.getElementById('friendSearch').onkeydown=e=>{if(e.key==='Enter')searchFriend()};document.querySelectorAll('#store [data-home],#profile [data-home],#friends [data-home]').forEach(b=>b.onclick=()=>DF.show?.('home'));
const set=document.querySelector('#settings .card.list');if(set){const row=document.createElement('div');row.className='set-row';row.innerHTML='<div><b>Account</b><small>Sign out on this device</small></div><button class="secondary" id="logoutBtn">LOG OUT</button>';set.appendChild(row);row.querySelector('#logoutBtn').onclick=async()=>{try{if(S())await S().auth.signOut()}finally{Object.assign(P.profile,{id:null,display_name:'PLAYER',coins:500,xp:0,rank:1,mp_wins:0,mp_losses:0,bot_wins:0,settings:{},bio:'',showcase_weapon:'sword'});P.items=[];ready=false;DF.show?.('authScreen')}}}
setInterval(()=>{if(document.getElementById('friends')?.classList.contains('active'))refreshFriends()},5000)
}
function render(){const p=P.profile,sc=document.getElementById('storeCoins');if(sc)sc.textContent=(p.coins||0).toLocaleString();const pn=document.getElementById('profileName');if(pn)pn.textContent=p.display_name||'PLAYER';const pa=document.getElementById('profileAvatar');if(pa)pa.textContent=(p.display_name||'?')[0];const pr=document.getElementById('profileRank');if(pr)pr.textContent='RANK '+(p.rank||1);const xp=document.getElementById('profileXp');if(xp)xp.textContent=p.xp||0;const wi=document.getElementById('profileWins');if(wi)wi.textContent=p.mp_wins||0;const lo=document.getElementById('profileLosses');if(lo)lo.textContent=p.mp_losses||0;const bio=document.getElementById('profileBio');if(bio&&document.activeElement!==bio)bio.value=p.bio||'';const sw=document.getElementById('showcaseWeapon');if(sw&&DF.WEAPONS){if(!sw.options.length)sw.innerHTML=Object.values(DF.WEAPONS).map(w=>`<option value="${w.id}">${w.name}</option>`).join('');sw.value=p.showcase_weapon||'sword'}const el=document.getElementById('equippedList');if(el){const gear=catalogRows().filter(c=>owned(c.id)?.equipped).map(c=>`<div>${itemIcon(c)}<span><b>${c.name}</b><small>Level ${owned(c.id).level} · ${c.category}</small></span></div>`).join('');el.innerHTML=`<div class="showcase-card">${DF.WEAPONS&&DF.WEAPONS[p.showcase_weapon]?`<b>${DF.WEAPONS[p.showcase_weapon].name}</b>`:'Sword'}<small>Showcase weapon</small></div>`+(gear||'<small>Nothing equipped yet.</small>')}
const g=document.getElementById('storeGrid');if(!g)return;g.innerHTML=catalogRows().map(c=>{const i=owned(c.id),lv=i?i.level:0,cost=i?c.upgrade*lv:c.price,max=lv>=c.max;return `<article class="store-item ${i?'owned':''}">${itemIcon(c)}<div class="store-cat">${c.category.replace('_',' ')}</div><h3>${c.name}</h3><p>${c.desc}</p><div class="store-level">${i?`LEVEL ${lv}/${c.max}`:'LOCKED'}</div><small>${i&&c.upgrade?`Next level: ${cost} coins`:'Price '+c.price}</small><div class="store-actions"><button data-act="${i?(max?'equip':'upgrade'):'buy'}" data-id="${c.id}" class="${i&&i.equipped?'secondary':'primary'}">${i?(max?(i.equipped?'EQUIPPED':'EQUIP'):'UPGRADE '+cost):'BUY '+c.price}</button></div></article>`}).join('');g.querySelectorAll('button').forEach(b=>b.onclick=async()=>{const msg=document.getElementById('storeMsg');b.disabled=true;try{if(b.dataset.act==='buy')await buy(b.dataset.id);else if(b.dataset.act==='upgrade')await upgrade(b.dataset.id);else await equip(b.dataset.id);msg.className='message';msg.textContent='Forge updated.'}catch(e){msg.className='message bad';msg.textContent=e.message||'Forge action failed.'}finally{b.disabled=false;render()}})}
inject();DF.Progression={state:P,catalog:CATALOG,load,owned,item,combat,setName,setSettings,saveProfileExtras,claim,leaderboard,buy,upgrade,equip,ready:()=>ready,refreshFriends,createDuelRequest,respondDuel,onChange:null};window.addEventListener('DOMContentLoaded',load);
})();
